image: registry.gitlab.com/gbraad/centos:7

before_script:
  - yum -y install git epel-release "@Development Tools"
  - yum -y install createrepo mock redhat-rpm-config rpmdevtools
  - yum -y install openssl openssl-devel bc

pages:
  script:
  - mkdir public
  - git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git --depth 1
  - cp config linux/.config
  - cd linux
  - make olddefconfig
  - make rpm
  - cd ..
  - mv /root/rpmbuild/RPMS/x86_64/* ./public
  - mv /root/rpmbuild/SRPMS/* ./public
  - createrepo --database ./public
  - ls ./public/ | ./genindex.sh > ./index.html
  - mv ./index.html ./public
  - mv ./kernel-mainline.repo ./public
  artifacts:
    paths:
    - public
  only:
  - master
